export interface Language {
  id: string
  name: string
  extension: string
}

export const LANGUAGES: Language[] = [
  { id: 'text', name: 'Plain Text', extension: '.txt' },
  { id: 'markdown', name: 'Markdown', extension: '.md' },
  { id: 'javascript', name: 'JavaScript', extension: '.js' },
  { id: 'typescript', name: 'TypeScript', extension: '.ts' },
  { id: 'python', name: 'Python', extension: '.py' },
  { id: 'rust', name: 'Rust', extension: '.rs' },
  { id: 'go', name: 'Go', extension: '.go' },
  { id: 'java', name: 'Java', extension: '.java' },
  { id: 'c', name: 'C', extension: '.c' },
  { id: 'cpp', name: 'C++', extension: '.cpp' },
  { id: 'csharp', name: 'C#', extension: '.cs' },
  { id: 'php', name: 'PHP', extension: '.php' },
  { id: 'ruby', name: 'Ruby', extension: '.rb' },
  { id: 'swift', name: 'Swift', extension: '.swift' },
  { id: 'kotlin', name: 'Kotlin', extension: '.kt' },
  { id: 'scala', name: 'Scala', extension: '.scala' },
  { id: 'r', name: 'R', extension: '.r' },
  { id: 'julia', name: 'Julia', extension: '.jl' },
  { id: 'lua', name: 'Lua', extension: '.lua' },
  { id: 'perl', name: 'Perl', extension: '.pl' },
  { id: 'haskell', name: 'Haskell', extension: '.hs' },
  { id: 'elixir', name: 'Elixir', extension: '.ex' },
  { id: 'clojure', name: 'Clojure', extension: '.clj' },
  { id: 'fsharp', name: 'F#', extension: '.fs' },
  { id: 'dart', name: 'Dart', extension: '.dart' },
  { id: 'zig', name: 'Zig', extension: '.zig' },
  { id: 'html', name: 'HTML', extension: '.html' },
  { id: 'css', name: 'CSS', extension: '.css' },
  { id: 'scss', name: 'SCSS', extension: '.scss' },
  { id: 'less', name: 'Less', extension: '.less' },
  { id: 'jsx', name: 'JSX', extension: '.jsx' },
  { id: 'tsx', name: 'TSX', extension: '.tsx' },
  { id: 'vue', name: 'Vue', extension: '.vue' },
  { id: 'svelte', name: 'Svelte', extension: '.svelte' },
  { id: 'astro', name: 'Astro', extension: '.astro' },
  { id: 'mdx', name: 'MDX', extension: '.mdx' },
  { id: 'json', name: 'JSON', extension: '.json' },
  { id: 'yaml', name: 'YAML', extension: '.yaml' },
  { id: 'toml', name: 'TOML', extension: '.toml' },
  { id: 'xml', name: 'XML', extension: '.xml' },
  { id: 'ini', name: 'INI', extension: '.ini' },
  { id: 'graphql', name: 'GraphQL', extension: '.graphql' },
  { id: 'bash', name: 'Bash', extension: '.sh' },
  { id: 'powershell', name: 'PowerShell', extension: '.ps1' },
  { id: 'fish', name: 'Fish', extension: '.fish' },
  { id: 'dockerfile', name: 'Dockerfile', extension: '' },
  { id: 'terraform', name: 'Terraform', extension: '.tf' },
  { id: 'sql', name: 'SQL', extension: '.sql' },
  { id: 'prisma', name: 'Prisma', extension: '.prisma' },
  { id: 'latex', name: 'LaTeX', extension: '.tex' },
  { id: 'diff', name: 'Diff', extension: '.diff' },
  { id: 'makefile', name: 'Makefile', extension: '' },
  { id: 'nginx', name: 'Nginx', extension: '.conf' },
  { id: 'objective-c', name: 'Objective-C', extension: '.m' },
  { id: 'ocaml', name: 'OCaml', extension: '.ml' },
  { id: 'pascal', name: 'Pascal', extension: '.pas' },
  { id: 'erlang', name: 'Erlang', extension: '.erl' },
  { id: 'fortran-free-form', name: 'Fortran', extension: '.f90' },
  { id: 'groovy', name: 'Groovy', extension: '.groovy' },
  { id: 'lisp', name: 'Lisp', extension: '.lisp' },
  { id: 'scheme', name: 'Scheme', extension: '.scm' },
  { id: 'racket', name: 'Racket', extension: '.rkt' },
  { id: 'solidity', name: 'Solidity', extension: '.sol' },
  { id: 'verilog', name: 'Verilog', extension: '.v' },
  { id: 'vhdl', name: 'VHDL', extension: '.vhd' },
  { id: 'wasm', name: 'WebAssembly', extension: '.wat' },
  { id: 'asm', name: 'Assembly', extension: '.asm' },
  { id: 'coffeescript', name: 'CoffeeScript', extension: '.coffee' },
  { id: 'crystal', name: 'Crystal', extension: '.cr' },
  { id: 'd', name: 'D', extension: '.d' },
  { id: 'handlebars', name: 'Handlebars', extension: '.hbs' },
  { id: 'nix', name: 'Nix', extension: '.nix' },
  { id: 'pug', name: 'Pug', extension: '.pug' },
  { id: 'sass', name: 'Sass', extension: '.sass' },
  { id: 'stylus', name: 'Stylus', extension: '.styl' },
  { id: 'tcl', name: 'Tcl', extension: '.tcl' },
  { id: 'viml', name: 'Vim Script', extension: '.vim' },
  { id: 'ada', name: 'Ada', extension: '.adb' },
  { id: 'apex', name: 'Apex', extension: '.cls' },
  { id: 'awk', name: 'AWK', extension: '.awk' },
  { id: 'bat', name: 'Batch', extension: '.bat' },
  { id: 'cobol', name: 'COBOL', extension: '.cob' },
  { id: 'csv', name: 'CSV', extension: '.csv' },
  { id: 'glsl', name: 'GLSL', extension: '.glsl' },
  { id: 'hlsl', name: 'HLSL', extension: '.hlsl' },
  { id: 'jsonc', name: 'JSON with Comments', extension: '.jsonc' },
  { id: 'log', name: 'Log', extension: '.log' },
  { id: 'mermaid', name: 'Mermaid', extension: '.mmd' },
  { id: 'plsql', name: 'PL/SQL', extension: '.pls' },
  { id: 'postcss', name: 'PostCSS', extension: '.pcss' },
  { id: 'proto', name: 'Protocol Buffers', extension: '.proto' },
  { id: 'puppet', name: 'Puppet', extension: '.pp' },
  { id: 'purescript', name: 'PureScript', extension: '.purs' },
  { id: 'regex', name: 'Regex', extension: '' },
  { id: 'rst', name: 'reStructuredText', extension: '.rst' },
  { id: 'smalltalk', name: 'Smalltalk', extension: '.st' },
  { id: 'sparql', name: 'SPARQL', extension: '.rq' },
  { id: 'systemverilog', name: 'SystemVerilog', extension: '.sv' },
  { id: 'twig', name: 'Twig', extension: '.twig' },
  { id: 'vb', name: 'VB.NET', extension: '.vb' },
  { id: 'wgsl', name: 'WGSL', extension: '.wgsl' },
]

export const LANGUAGE_IDS = LANGUAGES.map((l) => l.id)

export function getLanguageById(id: string): Language | undefined {
  return LANGUAGES.find((l) => l.id === id)
}

export function getLanguageName(id: string): string {
  return getLanguageById(id)?.name ?? id
}
